version: "3.9"

services:
  backend:
    build: .
    container_name: tienda_backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: tienda_db
    restart: always
    environment:
      POSTGRES_USER: tienda_user
      POSTGRES_PASSWORD: tienda_pass
      POSTGRES_DB: tienda_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
